// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/http/interfaces/httpcontext/httpcontext.go

// Package mock_httpcontext is a generated GoMock package.
package mock_httpcontext

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	httpcontext "github.com/supermetrolog/framework/pkg/http/interfaces/httpcontext"
)

// MockResponse is a mock of Response interface.
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
}

// MockResponseMockRecorder is the mock recorder for MockResponse.
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance.
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// Content mocks base method.
func (m *MockResponse) Content() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Content")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Content indicates an expected call of Content.
func (mr *MockResponseMockRecorder) Content() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Content", reflect.TypeOf((*MockResponse)(nil).Content))
}

// Headers mocks base method.
func (m *MockResponse) Headers() map[string][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headers")
	ret0, _ := ret[0].(map[string][]string)
	return ret0
}

// Headers indicates an expected call of Headers.
func (mr *MockResponseMockRecorder) Headers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headers", reflect.TypeOf((*MockResponse)(nil).Headers))
}

// StatusCode mocks base method.
func (m *MockResponse) StatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// StatusCode indicates an expected call of StatusCode.
func (mr *MockResponseMockRecorder) StatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusCode", reflect.TypeOf((*MockResponse)(nil).StatusCode))
}

// MockResponseWriter is a mock of ResponseWriter interface.
type MockResponseWriter struct {
	ctrl     *gomock.Controller
	recorder *MockResponseWriterMockRecorder
}

// MockResponseWriterMockRecorder is the mock recorder for MockResponseWriter.
type MockResponseWriterMockRecorder struct {
	mock *MockResponseWriter
}

// NewMockResponseWriter creates a new mock instance.
func NewMockResponseWriter(ctrl *gomock.Controller) *MockResponseWriter {
	mock := &MockResponseWriter{ctrl: ctrl}
	mock.recorder = &MockResponseWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseWriter) EXPECT() *MockResponseWriterMockRecorder {
	return m.recorder
}

// AddHeader mocks base method.
func (m *MockResponseWriter) AddHeader(key, value string) httpcontext.ResponseWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHeader", key, value)
	ret0, _ := ret[0].(httpcontext.ResponseWriter)
	return ret0
}

// AddHeader indicates an expected call of AddHeader.
func (mr *MockResponseWriterMockRecorder) AddHeader(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeader", reflect.TypeOf((*MockResponseWriter)(nil).AddHeader), key, value)
}

// HtmlResponse mocks base method.
func (m *MockResponseWriter) HtmlResponse() (httpcontext.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HtmlResponse")
	ret0, _ := ret[0].(httpcontext.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HtmlResponse indicates an expected call of HtmlResponse.
func (mr *MockResponseWriterMockRecorder) HtmlResponse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HtmlResponse", reflect.TypeOf((*MockResponseWriter)(nil).HtmlResponse))
}

// JsonResponse mocks base method.
func (m *MockResponseWriter) JsonResponse() (httpcontext.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JsonResponse")
	ret0, _ := ret[0].(httpcontext.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JsonResponse indicates an expected call of JsonResponse.
func (mr *MockResponseWriterMockRecorder) JsonResponse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JsonResponse", reflect.TypeOf((*MockResponseWriter)(nil).JsonResponse))
}

// SetContent mocks base method.
func (m *MockResponseWriter) SetContent(arg0 any) httpcontext.ResponseWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetContent", arg0)
	ret0, _ := ret[0].(httpcontext.ResponseWriter)
	return ret0
}

// SetContent indicates an expected call of SetContent.
func (mr *MockResponseWriterMockRecorder) SetContent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContent", reflect.TypeOf((*MockResponseWriter)(nil).SetContent), arg0)
}

// SetStatusCode mocks base method.
func (m *MockResponseWriter) SetStatusCode(arg0 int) httpcontext.ResponseWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatusCode", arg0)
	ret0, _ := ret[0].(httpcontext.ResponseWriter)
	return ret0
}

// SetStatusCode indicates an expected call of SetStatusCode.
func (mr *MockResponseWriterMockRecorder) SetStatusCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusCode", reflect.TypeOf((*MockResponseWriter)(nil).SetStatusCode), arg0)
}

// XmlResponse mocks base method.
func (m *MockResponseWriter) XmlResponse() (httpcontext.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XmlResponse")
	ret0, _ := ret[0].(httpcontext.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XmlResponse indicates an expected call of XmlResponse.
func (mr *MockResponseWriterMockRecorder) XmlResponse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XmlResponse", reflect.TypeOf((*MockResponseWriter)(nil).XmlResponse))
}

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// Param mocks base method.
func (m *MockContext) Param(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Param", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// Param indicates an expected call of Param.
func (mr *MockContextMockRecorder) Param(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Param", reflect.TypeOf((*MockContext)(nil).Param), key)
}

// Request mocks base method.
func (m *MockContext) Request() *http.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request")
	ret0, _ := ret[0].(*http.Request)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockContextMockRecorder) Request() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockContext)(nil).Request))
}

// ResponseWriter mocks base method.
func (m *MockContext) ResponseWriter() httpcontext.ResponseWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseWriter")
	ret0, _ := ret[0].(httpcontext.ResponseWriter)
	return ret0
}

// ResponseWriter indicates an expected call of ResponseWriter.
func (mr *MockContextMockRecorder) ResponseWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseWriter", reflect.TypeOf((*MockContext)(nil).ResponseWriter))
}
